### ISSUE TITLE
Publishing to WCH fails / missing content types

### ISSUE THREAD

**Issue by zuchowski** [ibm-wch/wch-site-application#1]
When i try to publish content to WCH it fails on reference to Content Types.  It looks like there are missing definition of content types. 

for example:

"type": {
    "id": "9aeeecef-85ce-4d41-a797-1ad27735d0cb",
    "name": "List"
  },

[wchtools-cli.txt](https://github.com/ibm-wch/wch-site-application/files/1314586/wchtools-cli.txt)

**Comment by ThomasHurek** [comment]
Did you create a new WCH tenant after September 18th or use an existing one? For a content hub created before September 18th you first need to deploy all the artifacts stored here: https://greenhouse.lotus.com/plugins/plugincatalog.nsf/assetDetails.xsp?action=editDocument&documentId=B444A62EB5379C988525819C0021A994

**Comment by mburati** [comment]
Thomas' answer is correct, but I just wanted to add some more tips and clarification, in case it helps for future questions:

 - The above was a wchtools "push" issue (importing artifacts into WCH), not "publish".
 - Publish is the term for WCH moving ready items from the authoring system to the delivery system.
 - If you have any future issues with wchtools, the wchtools-api.log includes more information about actual HTTP responses from the WCH APIs (vs the CLI output in wchtools-cli.log).   Please be careful though, to verify that any logs you upload don't include any private or sensitive information.

I hope that information helps going forward.

**Comment by zuchowski** [comment]
Yes, this is environment created 1 month ago and I did not installed artifacts from greenhouse. I can see that missing items are in the link you have mentioned. Thank You
